server:
  port: 8088

# MySQL
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:23306/test
    username: root
    password: ibjang123
  # Debug SQL query
  jpa:
    show-sql: true
    properties:
#      use_sql_comments: true
      hibernate.format_sql: true
#      hibernate:
#        default_batch_fetch_size: 500
    hibernate:
      ddl-auto: create
    open-in-view: off

logging:
  level:
    org:
      hibernate:
#        SQL: debug
        type: trace